name = "DoubleBetaDecayGenerators"
uuid = "b67d9115-b479-4391-b710-1f027b87ba2b"
license = "MIT"
authors = ["Luigi Pertoldi <gipert@pm.me>", "Yuan-Ru Lin <yuanru@uw.edu>"]
description = "A Julia package to generate double beta decays."
version = "0.1.0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
EmpiricalDistributions = "0bbb1fad-0f24-45fe-94a4-415852c5cc3b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
Geant4 = "559df036-b7a0-42fd-85df-7d5dd9d70f44"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extensions]
DoubleBetaDecayGeneratorsGeant4Ext = ["Geant4", "StaticArrays"]

[compat]
Artifacts = "^1.10"
DelimitedFiles = "^1.10"
EmpiricalDistributions = "0.3.9"
LinearAlgebra = "<0.0.1, 1"
Printf = "<0.0.1, 1"
ProgressMeter = "1.10"
Random = "<0.0.1, 1"
Rotations = "1.7"
StatsBase = "0.34"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
